### ISSUE TITLE
因Windows系统缩放所导致的文字错位问题

### ISSUE THREAD

**Issue by Tiredauir** [PLFJY/idv-bp-asg-e#1]
在不同的分辨率下 使用不同的缩放比例（如100% 150% 200%）会导致各面板中可能出现的文字错位
如果出现该问题 我的解决方法是调整缩放比例 找到合适的不会错位的缩放比例
应该在项目描述中添加这一提示 我也是捣鼓半天才找到原因的 毕竟不同的人使用的分辨率和缩放比例不同

**Comment by PLFJY** [comment]
请使用新的项目 plfjy/bp-sys-wpf 此项目已停止维护

**Comment by PLFJY** [comment]
而且由于易语言的UI库过老我也无法解决这种问题

**Comment by PLFJY** [comment]
我会加到README.MD里的
